services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - mern-ttt

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./backend/:/app
      - /app/node_modules
    networks:
      - mern-ttt
networks:
  mern-ttt:
    driver: bridge
